apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gcpLearning
  description: >
    Exploration of GCP with Terraform.
  annotations:
    github.com/project-slug: linuxlsr/gcpLearning
  tags:
    - gcp
    - terraform
spec:
  type: other
  lifecycle: experimental
  owner: user:linuxlsr
